version: '3.8'

services:
  config-server:
    build:
      context: ./configServer
      dockerfile: Dockerfile
    container_name: config-server
    networks:
        - EurekaNet
    ports:
      - "8888:8888"

  eureka-server:
      build:
        context: ./eurekaServer
        dockerfile: Dockerfile
      container_name: eureka-server
      ports:
        - "8761:8761"
      networks:
            - EurekaNet
      depends_on:
        - config-server
networks:
  EurekaNet:
    driver: bridge


