version: '3.8'

services:
  config-server:
    build:
      context: ./configServer
      dockerfile: Dockerfile
    container_name: config-server
    networks:
        - EurekaNet
    ports:
      - "8888:8888"

  eureka-server:
      build:
        context: ./eurekaServer
        dockerfile: Dockerfile
      container_name: eureka-server
      ports:
        - "8761:8761"
      networks:
            - EurekaNet
  book-service:
    build:
      context: ./BooksServices
      dockerfile: Dockerfile
    container_name: book-service
    environment:
        - SPRING_PROFILES_ACTIVE=production
    networks:
        - EurekaNet
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka-server

  user-service:
    build:
      context: ./useService
      dockerfile: Dockerfile
    container_name: user-service
    environment:
        - SPRING_PROFILES_ACTIVE=production
    networks:
        - EurekaNet
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server

  rent-book-service:
    build:
      context: ./RentBooksService
      dockerfile: Dockerfile
    container_name: rent-book-service
    environment:
        - SPRING_PROFILES_ACTIVE=production
    networks:
        - EurekaNet
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - eureka-server
networks:
  EurekaNet:
    driver: bridge


